const Action = {

    GET_DATA_REQUEST : "GET_DATA_REQUEST", 
    GET_DATA_SUCCESS : "GET_DATA_SUCCESS", 
    GET_DATA_FAILURE : "GET_DATA_FAILURE", 
    PATCH_DATA_REQUEST : "PATCH_DATA_REQUEST", 
    PATCH_DATA_SUCCESS : "PATCH_DATA_SUCCESS", 
    PATCH_DATA_FAILURE : "PATCH_DATA_FAILURE", 
}

export {Action}